name: Generate PDF

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate PDF
        run: |
            sudo apt-get update
            sudo apt-get install -y texlive \
              texlive-fonts-recommended \
              texlive-fonts-extra \
              poppler-utils \
              texlive-xetex
            xelatex -8bit -halt-on-error resume.tex &&
            mv resume.pdf Sam_Al-Taiff-Resume.pdf &&
            pdftoppm -png Sam_Al-Taiff-Resume.pdf Sam_Al-Taiff-Resume &&
            mv Sam_Al-Taiff-Resume-1.png Sam_Al-Taiff-Resume.png

      - name: Release
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: |
            Sam_Al-Taiff-Resume.pdf
            Sam_Al-Taiff-Resume.png
